GET https://aluguel-eventos.onrender.com/products?search=
###
POST https://aluguel-eventos.onrender.com/products
Content-Type: application/json 

{
    "name": "Garfo",
    "description": "30 garfos de prata",
    "price": 85.90,
    "image": "url_garfo"
}
###
DELETE https://aluguel-eventos.onrender.com/products/3823a970-5b00-4de1-9616-36cf6d180d1f